markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Perry Naughton
url: http://perrynaughton.com
description: Perry's Personal Site
twitter: NaughtonPerry
github: PNaughton
gravatar_url: http://www.gravatar.com/avatar/43dbcc9f8b881754cfd3284f10b813d2
